# Generated by Django 5.0.4 on 2024-04-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-fecha_agregado']},
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_agregado',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
