# Generated by Django 5.0.4 on 2024-04-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cliente_options_cliente_fecha_agregado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_agregado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
