# Generated by Django 5.0.4 on 2024-05-03 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cliente_fecha_agregado_alter_entrada_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cuentacontablecliente',
            name='fecha_apertura',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='sesion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sesion'),
        ),
    ]
